### ISSUE TITLE
Add dependabot.yml file to the project

### ISSUE THREAD

**Issue by dhruvsaxena1998** [dhruvsaxena1998/un-named#18]
--- Required ---
package-ecosystem: npm
directory: '/'

--- Location ---
.github/depedabot.yml

**Comment by sameerkavthekar** [comment]
Hey can I work on this

**Comment by zahrafalah** [comment]
I am interested in this issue

**Comment by dhruvsaxena1998** [comment]
Hi, both of you. I can only merge one PR but I've created these simple issues to support #hacktoberfest. If you are working towards hacktober, you both can create PR :smiley:

**Comment by sameerkavthekar** [comment]
Hi @dhruvsaxena1998 , can you add the "hacktoberfest" topic to the repo so these PRs can count, please :smile:
