### ISSUE TITLE
Upgrade Strapi to v3.1.7

### ISSUE THREAD

**Issue by dhruvsaxena1998** [dhruvsaxena1998/un-named#19]
Current project is using strapi `v3.1.3`. Need to update it to latest available ( `3.1.7` at the moment).

Note: This project doesn't include any custom admin plugins so you can ignore the step

Migration Guide: [https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html)

### As project is already running on 3.1.x, you can ignore [2, 3, 4] Steps.

**Comment by SMAKSS** [comment]
Well, I would like to claim this one. 😁

**Comment by dhruvsaxena1998** [comment]
Go ahead man!
